### PR TITLE
Update JGit

### LINKED ISSUE #26: upgrade jgit library
_From @maks on May 26, 2016 4:56_

Currently using jgit:3.6.2.201501210735 whereas maven central already has available  jgit:4.4.0.201605250940-rc1

_Copied from original issue: sheimi/SGit#182_

### PR DESCRIPTION
**Pull request by kaeptmblaubaer1000**
Fixes #26.

### CODE REVIEW

**Comment by maks** [comment]
@kaeptmblaubaer1000 the build on TravisCI doesnt seem happy about something in the newer version of jgit. I guess it compiles fine for you locally?

**Comment by kaeptmblaubaer1000** [comment]
@maks no it currently doesn't.
I'll modify my fork of retropiler to fix this soon.
Retropiler currently force-applies Retrolambda, which doesn't support default interface methods which are used by JGit.
Android Desugar supports them, but it disables with Retrolambda.

**Comment by kaeptmblaubaer1000** [comment]
@maks but _now_ it compiles fine.

**Comment by maks** [comment]
@kaeptmblaubaer1000 thanks - I'll take a look at this soon

**Comment by kaeptmblaubaer1000** [comment]
@maks it's still not fine.
It still uses `File.toPath()`. I'll try to fix this using a custom Gradle plugin.

**Comment by inatz16** [comment]
😁

**Comment by kaeptmblaubaer1000** [comment]
I don't want to fix the merge problems and will move to another PR.

**Pull request closed without merging**
