### PR TITLE
Partial Spanish Translation (values-es)

### PR DESCRIPTION
**Pull request by JAngres**

### CODE REVIEW

**Comment by maks** [comment]
Thank you for contributing this. You seem to have not based off current master, I'll cherry pick your last commit and include it via a seperate PR.

**Comment by kaeptmblaubaer1000** [comment]
@maks have you done this?
If you have, then please close this.

**Comment by maks** [comment]
@kaeptmblaubaer1000 no its not, the last commit needs cherry picking out of this as this branch includes already merged commits

**Comment by maks** [comment]
replaced by #495

**Pull request closed without merging**
