### PR TITLE
fixed kotlin .kt files highlighting

### PR DESCRIPTION
**Pull request by rahulraopune**

### CODE REVIEW

**Comment by kaeptmblaubaer1000** [comment]
@rahulraopune but there is one thing to change: please add `.kts` (Kotlin Script) to the file extensions.

**Comment by rahulraopune** [comment]
Yes added i have added kts now

**Comment by rahulraopune** [comment]
@kaeptmblaubaer1000  please review . i have tested the code with the below .kts file

[https://github.com/gradle/kotlin-dsl/blob/master/plugins-experiments/build.gradle.kts](url)

**Comment by maks** [comment]
@rahulraopune thank you for contributing this.

**Comment by rahulraopune** [comment]
My Pleasure

**Pull request merged**
