### PR TITLE
Access to all files in order to read/write repos from external storage

### PR DESCRIPTION
**Pull request by prattpratt**
I completely can not use import external repos on my device running Android 12 (API 31). Access all files is required.

### CODE REVIEW

**Comment by maks** [comment]
Thank you very much for contributing this! 
This all looks good. 👍🏻  
I'l test this out and likely merge it asap.

**Comment by maks** [comment]
LGTM. Thanks again for contributing this.

**Comment by maks** [comment]
This is now available in the Beta channel of MGit on Google Play.
Fixes: #465 #610

**Comment by maks** [comment]
Actually the use of the permission is causing issues with the Google Play review of the new release so it's not yet available as I need to try to contact Google Play staff about this.

**Comment by prattpratt** [comment]
I've added a new PR #616.

**Comment by cognifloyd** [comment]
I joined the beta, but I don't see the update. Is Google play blocking it from hitting the beta channel too?

**Comment by maks** [comment]
@cognifloyd yes per #620 unfortunately until Google allows MGit to use the "all files" permission, this update cannot be published, even on the beta channel.

**Pull request merged**
