### PR TITLE
Update README badges

### PR DESCRIPTION
**Pull request by TacoTheDank**
dunno why the last thing counted as edited when i didnt even touch it

### CODE REVIEW

**Comment by TacoTheDank** [comment]
there we go

**Comment by kaeptmblaubaer1000** [comment]
@maks the last may count as edited because of the ending newline.
Did you add/remove it?

**Comment by maks** [comment]
no that's all fine, thanks again for contributing this update.

**Comment by TacoTheDank** [comment]
ye

**Pull request merged**
