### PR TITLE
Update editor to latest CodeMirror and highlight.js

### PR DESCRIPTION
**Pull request by kb-1000**

### CODE REVIEW

**Comment by maks** [comment]
@kb-1000 Travis.org seems to have been having issues, so I've now migrated to Travis.com per their migration instructions, seems to be working fine for me but looks like this PR may have got stuck, so you might just want to push a trivial change to your branch to see if that get Travis to kick off a build.

**Comment by kb-1000** [comment]
Ok, I squashed the commits onto master

**Comment by maks** [comment]
Unfortunately this seems to have broken long line handling:
device-2020-03-12-083420

**Comment by kb-1000** [comment]
I can't seem to manage to get it into the old form via CSS. I'll try something else later... would it be okay if I downgraded highlight.js to the version MGit is currently using?

**Comment by maks** [comment]
Yes sure, using same version of highlight.js as currently used is fine.

**Pull request closed without merging**
