### PR TITLE
resized icon for other sized and separated icon from logo #176

### PR DESCRIPTION
**Pull request by marukami**
I did my best creating all the densities for the icon. If you have the source asset, I could make the icon sharper. https://developer.android.com/guide/topics/resources/providing-resources.html says to use the mipmap resource folder, so I copied all the images into there.

I also added any missing densities for the logo.

### CODE REVIEW

**Comment by maks** [comment]
@marukami awesome thanks! My bad though, a better icon was contributed a while ago in: #89 but while I updated the Play listing with it, I hadn't got around to doing so for the app. Its a svg so should be easy to use. Sorry again for the double work!

**Comment by marukami** [comment]
An Illustrator SVG. Wonderful. I should be able to take that and export an Android Vector drawable. We can either use the AppCompat or have Android Studio generate PNG from the vector.

**Comment by maks** [comment]
@marukami excellent!
:+1: to using AppCompat for vector drawables.

**Comment by marukami** [comment]
So we can use a vector drawable inside the app at some point I simplified the icon to be more similar to the current icon. Shadows and composite shapes don't work well in vector drawables. I left the SVG in the doc and created an Ill Illustrator.

**Pull request merged**
