### PR TITLE
Feature: Update index / executable bit

### PR DESCRIPTION
**Pull request by kb-1000**

### CODE REVIEW

**Comment by maks** [comment]
@kaeptmblaubaer1000 apologies for taking so long to get back to you on this. 
Sorry I can't say I'm happy with the dialog as the need is really only to be able to set the executable bit for files and even that case seems rather a niche use case (from #109) so I'd like to restrict the functionality added to just that.

**Comment by kaeptmblaubaer1000** [comment]
Waiting for testing.

**Comment by maks** [comment]
@kaeptmblaubaer1000 sorry its taken me a while to get back to this. The code in the PR looks good!
Doing a quick test I ran into a few issues:
1. In an newly cloned repo (Downloads as root folder in settings), I added a new file, edited it with a small string then went back and tried to set it to be executable and this caused an exception:
```
java.lang.RuntimeException: An error occurred while executing doInBackground()
        at android.os.AsyncTask$3.done(AsyncTask.java:353)
        at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
        at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
        at java.util.concurrent.FutureTask.run(FutureTask.java:271)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)
     Caused by: org.eclipse.jgit.errors.LockFailedException: Cannot lock /storage/emulated/0/Download/Sandbox/.git/index
        at org.eclipse.jgit.dircache.DirCache.lock(DirCache.java:224)
        at org.eclipse.jgit.dircache.DirCache.lock(DirCache.java:301)
        at org.eclipse.jgit.dircache.DirCache.lock(DirCache.java:267)
        at org.eclipse.jgit.lib.Repository.lockDirCache(Repository.java:1052)
        at com.manichord.mgit.tasks.repo.UpdateIndexTask.updateIndex(UpdateIndexTask.kt:25)
        at com.manichord.mgit.tasks.repo.UpdateIndexTask.doInBackground(UpdateIndexTask.kt:20)
        at com.manichord.mgit.tasks.repo.UpdateIndexTask.doInBackground(UpdateIndexTask.kt:13)
        at android.os.AsyncTask$2.call(AsyncTask.java:333)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
```
2. Doing same in newly cloned repo, this time in default location. setting exe bit on an existing file seemed to work without error but when I checked afterwards I dont see any changes listed in the unstaged diff.

3. Trying to set exe bit on a newly created file edited to include a few chars in newly cloned repo in default location caused an exception:
```
E/SheimiAsyncTask: set error [2131624124] exception
    com.manichord.mgit.exceptions.NoSuchIndexPathException: testexe
        at com.manichord.mgit.tasks.repo.UpdateIndexTask.updateIndex(UpdateIndexTask.kt:36)
        at com.manichord.mgit.tasks.repo.UpdateIndexTask.doInBackground(UpdateIndexTask.kt:20)
        at com.manichord.mgit.tasks.repo.UpdateIndexTask.doInBackground(UpdateIndexTask.kt:13)
        at android.os.AsyncTask$2.call(AsyncTask.java:333)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)
```

**Comment by kaeptmblaubaer1000** [comment]
@maks thanks for the feedback!
Your 3. issue is expected (but should get an error message).
The 4. issue is related to a wrong try..finally range, it should include anything after the lock.
Your first issue failed to lock the index (`index.lock` existing), I'll have to look into this.
The unstaged diff only shows differences between your real files and the index, but (as `UpdateIndex` says) I'm writing directly into the index.

**Pull request merged**
