### PR TITLE
[WIP] Allow third-party apps to run git commands

### LINKED ISSUE #489: Executing repo sync commands from a third-party application
Actually, the functionality is described in #448 .
If necessary, I can duplicate here.

### PR DESCRIPTION
**Pull request by sandorex**
(This is same PR as https://github.com/maks/MGit/pull/630 but with correct branch, *sorry*)

This is a spiritual successor of PR #488 and will hopefully fix #489 and possibly help with https://github.com/denolehov/obsidian-git/issues/57

Although the code is very much work in progress i would appreciate tips as im really really new to kotlin and my android dev skills are rusty
Hope it's salvageable 😄

### CODE REVIEW

**Comment by sandorex** [comment]
Currently the best way i've got it working is using custom uris `mgit://`, running the commands from a third party app is as simple as running a link `mgit://pull`, if needed it would be relatively simple to implement parsing of query in the uri (ex. `mgit://pull?repo_local_path=test_repo&force=true`), but passing extras in the intent is possible too

There was not a lot to rework for this to work, the commit https://github.com/maks/MGit/pull/630/commits/5289e8c1b7edfd0a438c70d23704f06e888bdfde already works, has notification with progress stating the current operation and is only dismissed if it has succeded, otherwise stays until the user removes it\
There are places with placeholder text and a bit ugly code but i'd say it's useable with one annoying thing is empty activity that appears when any command is ran using this method, i don't know any fix for this at the moment except maybe getting the permission to draw over all apps (that is problematic in newer android versions) and making it a dialog like window with progress and stuff?

**Comment by maks** [comment]
Thank you for contributing this. I'll have a look at it once you feel its ready.
In terms of early feedback: I would not like to have something as generic as `mgit://pull` so I do think this implementation at the very least needs to be able to handle specifying the path to the local repo being acted upon.

**Comment by sandorex** [comment]
> I would not like to have something as generic as mgit://pull so I do think this implementation at the very least needs to be able to handle specifying the path to the local repo being acted upon.
That is only used for calling it, all additional options are currently provided using extras
I've added all options exposed in the constructors of `AddToStageTask`, `CheckoutFileTask`, `CommitChangesTask`, `PullTask`, `PushTask`

**Comment by kb-1000** [comment]
As of right now, I'm not seeing any sort of protection against a potential malicious app that might abuse this API.
IMO, users should be asked if they want to allow the other app to run an action before actually running it.

**Comment by sandorex** [comment]
> As of right now, I'm not seeing any sort of protection against a potential malicious app that might abuse this API. IMO, users should be asked if they want to allow the other app to run an action before actually running it.

Yes i agree, i have thought of that and i plan to ask the user to do task whatever it is each time, although annoying its much safer\
There may be a way to check which app is sending an intent and then whitelisting? Ill have a look into that later

**Comment by sandorex** [comment]
I underestimated the work required for this so i am going to close this for now, if anyone wants to take over feel free

**Comment by xeor** [comment]
Is "for now" still undefined @sandorex ? I'm looking around for a way to do git on android, and after hours of looking. This PR seams to be the best bet. Other options are either super slow (js implemenation, or "unsupported" (unofficial appstores))..

**Comment by sandorex** [comment]
> Is "for now" still undefined @sandorex ?

It's abandoned, there are too many things that require work, im using git inside termux now with tasker widgets so i do not need it anymore

**Pull request closed without merging**
