### PR TITLE
fix clone dialog crash

### LINKED ISSUE #342: fix crash when opening url via intent
caused by changes from #333
```
...
Caused by: java.lang.NullPointerException: Attempt to read from field 'android.widget.EditText me.sheimi.sgit.databinding.DialogCloneBinding.remoteURL' on a null object reference
        at me.sheimi.sgit.dialogs.CloneDialog.setUrl(CloneDialog.java:170)
        at me.sheimi.sgit.RepoListActivity.onCreate(RepoListActivity.java:100)
        at android.app.Activity.performCreate(Activity.java:6679)
```

### PR DESCRIPTION
**Pull request by maks**
This fixes #342 but more importantly finally begins the process of converting the app architecture to be  MVVM using Kotlin/Databinding/Rx along with notifications for long running operations.

The changes in this PR are only to use Kotlin and Databinding, use of Rx will come later.

This also converts the **Modal** clone dialog to a inline view to improve UX.

### CODE REVIEW

**Comment by kaeptmblaubaer1000** [comment]
@maks I've tested this, it effectively removes support for giving the clone a name that differs from the URL end.

**Comment by maks** [comment]
Thanks for testing it, but WIP stands for work in progress, so this is not actually finished, it was just to give you some advance notice of how I am refactoring the code base in case you were working on anything yourself.

**Comment by kaeptmblaubaer1000** [comment]
@maks you're right, but I wanted to give you a hint what has bugs and has to be fixed.

**Comment by maks** [comment]
Almost ready, I just have one more commit in progress to handle showing-hiding on screen keyboard correctly.

**Comment by kaeptmblaubaer1000** [comment]
@maks do we have to replace `kotlin-stdlib-jdk8` with `kotlin-stdlib-jdk7`?

**Comment by maks** [comment]
@kaeptmblaubaer1000 yes, per my commit message, it or Retrolambda or both interferes with Databinding.

**Pull request merged**
