### PR TITLE
fix (intent filter) : open repository if already present 

### PR DESCRIPTION
**Pull request by aldaircruz**

### CODE REVIEW

**Comment by aldaircruz** [comment]
I forgotten to extract the strings

**Comment by maks** [comment]
@aldaircruz dont worry about that, I can just flatten the PR into a single commit on merge and git is clever enough to handle this - just see what the "file changed" tab on this PR shows... :smile:

**Comment by maks** [comment]
@aldaircruz sorry took a little while to get back to this, thanks again for the contribution!

**Comment by aldaircruz** [comment]
@maks It ok, thanks!

**Pull request merged**
