### PR TITLE
updated gradle, some libs, added versions plugin

### PR DESCRIPTION
**Pull request by marukami**

### CODE REVIEW

**Comment by maks** [comment]
@marukami thanks for that. Looks good but has broken travis for some reason to do with accepting the license by the look of things, will need to look into it when I get a chance: https://github.com/travis-ci/travis-ci/issues/7110

**Comment by marukami** [comment]
I think I see what I missed. The [travis.yml](https://github.com/maks/MGit/blob/master/.travis.yml) has `build-tools-25.0.0` and I've bumped it to `build-tools-25.0.3`. Just got to work. I'll try pushing a update to the YML at lunch.

**Comment by marukami** [comment]
Good to know. It was the Travis YML.

**Comment by maks** [comment]
Excellent, I've been meaning to do this for a while, thanks again @marukami

**Pull request merged**
