### PR TITLE
Russian translation added

### PR DESCRIPTION
**Pull request by BM835**
Russian translation (values-ru) added

### CODE REVIEW

**Comment by kaeptmblaubaer1000** [comment]
🤔 why the hell is this broken...

**Comment by maks** [comment]
@BM835  thanks you very much for contributing this. I'm a Russina speaker myself but just had not gotten around to doing this translation.
And thanks to @kaeptmblaubaer1000 for spotting the issue with Travis build's need to have the git plugin, though I have no idea why that is.

Unfortunately there still seems to be an issue with this PR to do with one of the translated items:
```
/home/travis/build/maks/MGit/app/src/main/res/values-ru/strings.xml:21:67: Error: Attribute name "пароль" associated with an element type "енить" must be followed by the ' = ' character.
```

**Comment by BM835** [comment]
@maks travis ci passed, there are no errors

**Comment by maks** [comment]
@BM835 thanks again for your contribution, will be included in the next release.

**Pull request merged**
